name: iOS Test

on:
  push:
    branches: [ "ci-test" ]

jobs:
  test-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.10'
      - uses: ./.github/actions/setup-java
      - run: ./scripts/bootstrap.sh
        working-directory: iosApp
      - run: xcodebuild -version
      - run: ./scripts/test.sh
        working-directory: iosApp