name: iOS Test

on:
  push:
    branches: [ "ci-test" ]

jobs:
  test-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install dependencies
        run: gem install nokogiri
      - uses: ./.github/actions/setup-java
      - run: ./scripts/bootstrap.sh
        working-directory: iosApp
      - run: ./scripts/test.sh
        working-directory: iosApp